#!/bin/bash
#
# Install diaspora dependencies i. e., what apt-get will do
#

grep -v '^#' /etc/apt/sources.list | grep -q universe || {
    cat <<- EOF
	"Warning: it looks like you have not enabled universe in your
	/etc/apt/sources.list. Most likely, this means trouble.
	But I will try anyway.
	EOF
    sleep 2
}
release=$( lsb_release -a | awk '/Release:/ {print $2}')

sudo apt-get update
sudo apt-get install --no-install-recommends -qy \
    build-essential            \
    git-core                   \
    imagemagick                \
    libmagick9-dev             \
    libssl_dev                 \
    libxml2                    \
    libxslt1-dev               \
    mongodb                    \
    openjdk-6-jre-headless     \
    python-software-properties \
    rake                       \
    ruby-dev                   \
    ruby-full


if [ "$release" = "10.04" ]; then
    # See: https://bugs.launchpad.net/ubuntu/+source/mongodb/+bug/557024
    sudo apt-get install xulrunner-1.9
    xulversion=$( xulrunner --gre-version)
    sudo ln -sf "/usr/lib/xulrunner-$xulversion/libmozjs.so" /usr/lib
fi
sudo add-apt-repository ppa:maco.m/ruby
sudo apt-get update
sudo apt-get install -qy rubygems
sudo gem install bundler  --bindir /usr/local/bin
