#!/bin/bash
#
#  Do what's needed to initiate diaspora.
#
#  Usage: sudo diaspora-setup [external hostname] [first user pw]
#
export PATH=$PATH:/usr/local/bin

arg_hostname="$1"
arg_pw="$2"

path=$( readlink -fn $0) && cd $(dirname $path)/../.. || \
    cd /usr/share/diaspora/master

test  "$( perl -e 'print $<')" = "0" || {
    echo "You need to be root to do this, giving up"
    exit 2
}

. pkg/source/funcs.sh


services=$( netstat -nl | grep '[^:]:3000[ \t]')
test -n "$services" && {
    echo "Warning: something is already using port 3000"
    echo "     $services"
}

service mongodb stop || :
rm -f /var/lib/mongodb/mongod.lock
service mongodb start || :

update-rc.d redis-server remove
/etc/init.d/redis-server stop

cd /usr/share/diaspora/master

libdir="/usr/lib"
[[ $(arch) == "x86_64" ]] && libdir="/usr/lib64"

rm -rf vendor
ln -s $libdir/diaspora-bundle/vendor .
ln -sf $libdir/diaspora-bundle/Gemfile .
ln -sf $libdir/diaspora-bundle/Gemfile.lock .

mkdir -p /var/run/diaspora
chown diaspora /var/run/diaspora

test -e config/app_config.yml ||
    cp config/app_config.yml.example config/app_config.yml

[ -e  lib/tasks/jasmine.rake ] &&
    sudo mv lib/tasks/jasmine.rake lib/tasks/jasmine.no-rake

cp pkg/ubuntu/diaspora-daemon script

redis_config

init_appconfig config/app_config.yml $arg_hostname

init_db $arg_pw|| {
    cat <<- EOF
	Database config failed. You might want to
	 - Check that mongod is running: service mongodb status
	 - Repair database files: mongod --repair
	 - Drop the diaspora mongo database:
	         % bundle exec rake db:purge
	 - Remove all db files: rm -rf /var/lib/mongodb/*
	 - Reset the config file by
	     'cp config/app_config.yml.example config/app_config.yml'
	EOF
}

init_public

chown -R diaspora /var/log/diaspora


sed -i '/socket_pidfile:/s|:.*|: /var/run/diaspora/diaspora-wsd.pid|' \
    config/app_config.yml

