#!/bin/sh
#
# Install  an ubuntu bundle package.
#
Usage='diaspora-bundle-install <diaspora-bundle-VERSION-RELEASE.tar.gz'

test "$(perl -e 'print $>')" = "0" || {
    echo "You need to be root to do this, giving up"
    exit 2
}

test $# -eq 1 || { echo $Usage; exit 2; }

test -r "$1" || { echo "Cannot open $1" exit 2; }

rm -rf /usr/lib/diaspora-bundle
tar xzf $1 -C /usr/lib

cd /usr/lib
mv $(basename $1 .tar.gz) diaspora-bundle

mkdir -p /usr/share/doc/diaspora-bundle || :
cd /usr/lib/diaspora-bundle
cp -a AUTHORS GNU-AGPL-3.0 COPYRIGHT Gemfile Gemfile.lock \
     /usr/share/doc/diaspora-bundle
cp -ar docs /usr/share/doc/diaspora-bundle

bundle install --local --deployment --without ri rdoc


