#!/bin/bash
#
#  Do what's needed to initiate diaspora.
#
#  Usage: # ./diaspora-setup [external hostname] [password]
#
set -x
export PATH=$PATH:/usr/local/bin

arg_hostname="$1"

path=$( readlink -fn $0) && cd $(dirname $path)/../.. || \
    cd /usr/share/diaspora/master

. pkg/source/funcs.sh

test $UID = "0" || {
    echo "You need to be root to do this, giving up"
    exit 2
}

services=$( netstat -nl | grep '[^:]:3000[ \t]')
test -n "$services" && {
    echo "Warning: something is already using port 3000"
}

mongodb_config /etc/mongodb.conf
/sbin/service mongod start || :

[[ ! -e config/redis.conf || /etc/redis.conf -nt config/redis.conf ]] &&
    redis_config
service redis stop || :
chkconfig redis off

libdir=$(rpm --eval %_libdir)
rm -rf vendor
ln -s $libdir/diaspora-bundle/vendor .
ln -sf $libdir/diaspora-bundle/Gemfile .
ln -sf $libdir/diaspora-bundle/Gemfile.lock .
ln -sf $libdir/diaspora-bundle/config .bundle/config

[ -e  lib/tasks/jasmine.rake ] &&
    sudo mv lib/tasks/jasmine.rake lib/tasks/jasmine.no-rake

[ -e config/app_config.yml ] || {
    cp config/app_config.yml.example config/app_config.yml
    init_appconfig config/app_config.yml $arg_hostname
    init_db "$2" || {
        cat <<- EOF
	Database config failed. You might want to
	 - Check that mongod is running: service mongodb status
	 - Repair database files: mongod --repair
	 - Drop the diaspora mongo database:
	       % bundle exec rake db:purge
	 - Remove all db files: rm -rf /var/lib/mongodb/*
	 - Reset the config file by
	     'cp config/app_config.yml.example config/app_config.yml'
	before making a new try
	EOF
    }
}

init_public
chown -R diaspora /var/log/diaspora
