#!/bin/bash
#
#  Install diaspora dependencies
#
#  Usage: diaspora-fedora13-setup
#
#  Synopsis, install:
#      $ git clone 'http://github.com/diaspora/diaspora-packages.git'
#      $ cd diaspora-packages/rvm
#      $ sudo diaspora-fedora13-setup
#
#  Installs all packages required by diaspora on Fedora 13.
#  Must run as root

test $UID = "0" || {
    echo "You need to be root to do this, giving up"
    exit 2
}

yum groupinstall -y "Development tools"

yum install  -y \
    curl                \
    git                 \
    iconv-devel         \
    ImageMagick         \
    java-1.6.0-openjdk  \
    libffi-devel        \
    libxml2-devel       \
    libxslt-devel       \
    libyaml-devel       \
    mongodb-server      \
    openssl-devel       \
    readline-devel      \
    redis               \
    sqlite-devel        \
    wget                \
    zlib-devel

chkconfig mongod on
service mongod start
